"""empty message

Revision ID: f1110feff932
Revises: fccc38bee901
Create Date: 2022-04-23 00:38:12.631546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1110feff932'
down_revision = 'fccc38bee901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=20), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('object', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('object', 'description_url',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('object', 'description_url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('object', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table('ticket')
    # ### end Alembic commands ###
